### ISSUE TITLE
드래그된 단어에 대한 유의어를 제공한다

### ISSUE THREAD

**Issue by tmddus2** [kopilot2024/kopilot#13]
## Feature Description

1. 유의어 API는 비싸서 CLOVA로 대체하기로 함.
2. 클로바로 요청

## To-Do

- [x] 유의어 API 알아보기
- [x] 클로바 스크립트 작성하기
- [x] 부분 수정과 연결
