### ISSUE TITLE
일정 시간 입력하지 않으면 글을 자동 저장한다

### ISSUE THREAD

**Issue by ttobe** [kopilot2024/kopilot#2]
## Feature Description
일정 시간 입력하지 않으면 글을 자동 저장한다

## To-Do
- [ ] 일정 시간이 입력이 없는 지 감지한다
- [x] 자동으로 3초마다 현재 값을 저장한다
- [x] 1분마다 버전으로 저장한다 

### 추가 사항
