### ISSUE TITLE
Fix: 긴 문장 관련 피드백 개선

### ISSUE THREAD

**Issue by tmddus2** [kopilot2024/kopilot#54]
## Feature Description

긴 문장 관련 피드백 부분을 반영한다. 입력이 제대로 되지 않는 부분을 개선한다.

## To-Do

- [x] 긴 문장 몇 문장 탐지됐는지 표시
- [x] 원문과 교정 결과 싱크 맞추기
- [x] `-` 로 나눠서 작성했을 때 다 붙어서 반영된다는 피드백 수정

### 추가 사항

여기에 작성하세요
