### ISSUE TITLE
오탈자 및 문법 오류를 감지한다

### ISSUE THREAD

**Issue by tmddus2** [kopilot2024/kopilot#6]
## Feature Description

문장이 마치면, 들어오는 맞춤법 검사 요청을 처리하는 서버를 구현한다.
검사 후 오탈자 및 문법 오류를 FE에 나타낸다.

## To-Do

- [x] Node js 설치 및 hanspell 설치
- [x] Nestjs로 요청을 처리하는 구조를 설계한다
  - [x] 3000 포트로 일단 진행
  - [x] API 명세 작성
  - [x] 문장이 들어오면, hanspell 처리 후 응답
  - [x] 반환 값에 대해 생각하기 - 토큰을 통해 칠하고, 파악을 할 것
- [x] 입력 받은 텍스트에서 API 요청 보낼 단위로 적절하게 나눈다 -> 문장단위
  - [x] 입력하거나 수정한 문장인지 어떻게 파악할지 정하기
  - [x] 맞춤법을 보낼 단위 문장을 어떻게 뽑아낼지 생각하기
  - [ ] 보내는 문장에만 정규식을 적용하거나 정확한 부분에 하이라이트를 칠하기
  - [ ] 테스트를 작성한다
- [x] 감지된 오류를 빨간색으로 표시한다 `FE`
  - [x] 응답에 대해 어떻게 프론트에서 색칠을 할 수 있을지 확인한다. -> editorjs 일단 테스트
  - [ ] 해당 빨간색을 클릭하면 창이 나오게 이벤트 alert만 시도하기

### 추가 사항
![흠 drawio](https://github.com/kopilot2024/kopilot/assets/101859033/f72c289f-4128-43a1-bdd0-590e64efdccf)
요청을 어떻게 처리할 것인가? 바로 요청을 보내면 왜 cors오류가 나올까?
-> 일단 다른걸 처리하고 추후에 수정하는 방향

![image](https://github.com/kopilot2024/kopilot/assets/101859033/2242ffef-a46a-4a77-aaaf-9458fb1fd357)
색칠
