### ISSUE TITLE
반복되는 어휘를 탐지한다

### ISSUE THREAD

**Issue by tmddus2** [kopilot2024/kopilot#60]
## Feature Description

작성한 글에서 반복되는 어휘를 탐지한다.

## To-Do

- [ ] 반복되는 어휘 탐지
- [ ] 교정제안 부분에 시각화해서 보여주기
- [ ] 유의어 제안과 연동

### 추가 사항

여기에 작성하세요
