### ISSUE TITLE
긴 문장을 감지한다

### ISSUE THREAD

**Issue by tmddus2** [kopilot2024/kopilot#8]
---
name: Feature Issue
about: 기능 관련 이슈 작성을 위한 템플릿입니다.
title: 'Feature: OO 구현'
labels: "feature"
assignees: ''

---

## Feature Description

사용자가 글을 입력할 때 글자수가 일정 수 이상 넘어가면 alert 띄우기

## To-Do

- [x] 개발을 위한 기본 페이지 만들기
    - [x] 텍스트 입력 부분 만들기
- [x] 텍스트 글자 수 70자 넘어가면 alert 띄우기
- [x] 100자 기준으로 긴 문장 감지. 화면에 반영
- [x] 긴 문장 탐지된 부분 클릭 시, 클로바 호출해서 나뉜 문장 받아오기
- [x] 팝업 띄우기
- [x] 사용자별로 긴 문장 기준 반영하도록 수정
